/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const QuizId = IDL.Nat;
export const Question = IDL.Record({
  'question' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'id' : QuizId,
  'questions' : IDL.Vec(Question),
});
export const LessonId = IDL.Nat;
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Category = IDL.Variant({
  'Business' : IDL.Null,
  'Design' : IDL.Null,
  'Programming' : IDL.Null,
  'Science' : IDL.Null,
});
export const CourseInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'difficulty' : Difficulty,
  'quiz' : Quiz,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'category' : Category,
});
export const CourseId = IDL.Nat;
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'difficulty' : Difficulty,
  'quiz' : Quiz,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'category' : Category,
});
export const Time = IDL.Int;
export const UserProgressView = IDL.Record({
  'quizScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'lastActiveDay' : Time,
  'weeklyActivity' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'completedLessons' : IDL.Vec(IDL.Nat),
  'learningStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createCourse' : IDL.Func([CourseInput], [], []),
  'getCourse' : IDL.Func([CourseId], [Course], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getDailyChallenge' : IDL.Func([], [Quiz], ['query']),
  'getLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
  'getQuiz' : IDL.Func([CourseId], [Quiz], ['query']),
  'getUserProgress' : IDL.Func([IDL.Principal], [UserProgressView], ['query']),
  'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
  'submitQuizAnswers' : IDL.Func([CourseId, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const QuizId = IDL.Nat;
  const Question = IDL.Record({
    'question' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({ 'id' : QuizId, 'questions' : IDL.Vec(Question) });
  const LessonId = IDL.Nat;
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Category = IDL.Variant({
    'Business' : IDL.Null,
    'Design' : IDL.Null,
    'Programming' : IDL.Null,
    'Science' : IDL.Null,
  });
  const CourseInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'difficulty' : Difficulty,
    'quiz' : Quiz,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'category' : Category,
  });
  const CourseId = IDL.Nat;
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'difficulty' : Difficulty,
    'quiz' : Quiz,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'category' : Category,
  });
  const Time = IDL.Int;
  const UserProgressView = IDL.Record({
    'quizScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'lastActiveDay' : Time,
    'weeklyActivity' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'completedLessons' : IDL.Vec(IDL.Nat),
    'learningStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    'createCourse' : IDL.Func([CourseInput], [], []),
    'getCourse' : IDL.Func([CourseId], [Course], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getDailyChallenge' : IDL.Func([], [Quiz], ['query']),
    'getLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
    'getQuiz' : IDL.Func([CourseId], [Quiz], ['query']),
    'getUserProgress' : IDL.Func(
        [IDL.Principal],
        [UserProgressView],
        ['query'],
      ),
    'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
    'submitQuizAnswers' : IDL.Func([CourseId, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };