/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Business' : null } |
  { 'Design' : null } |
  { 'Programming' : null } |
  { 'Science' : null };
export interface Course {
  'id' : CourseId,
  'title' : string,
  'duration' : bigint,
  'difficulty' : Difficulty,
  'quiz' : Quiz,
  'description' : string,
  'lessons' : Array<Lesson>,
  'category' : Category,
}
export type CourseId = bigint;
export interface CourseInput {
  'title' : string,
  'duration' : bigint,
  'difficulty' : Difficulty,
  'quiz' : Quiz,
  'description' : string,
  'lessons' : Array<Lesson>,
  'category' : Category,
}
export type Difficulty = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'content' : string,
}
export type LessonId = bigint;
export interface Question {
  'question' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface Quiz { 'id' : QuizId, 'questions' : Array<Question> }
export type QuizId = bigint;
export type Time = bigint;
export interface UserProgressView {
  'quizScores' : Array<[bigint, bigint]>,
  'lastActiveDay' : Time,
  'weeklyActivity' : Array<[bigint, bigint]>,
  'completedLessons' : Array<bigint>,
  'learningStreak' : bigint,
}
export interface _SERVICE {
  'createCourse' : ActorMethod<[CourseInput], undefined>,
  'getCourse' : ActorMethod<[CourseId], Course>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getDailyChallenge' : ActorMethod<[], Quiz>,
  'getLessons' : ActorMethod<[CourseId], Array<Lesson>>,
  'getQuiz' : ActorMethod<[CourseId], Quiz>,
  'getUserProgress' : ActorMethod<[Principal], UserProgressView>,
  'markLessonComplete' : ActorMethod<[CourseId, LessonId], undefined>,
  'submitQuizAnswers' : ActorMethod<[CourseId, Array<bigint>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];