/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CourseInput {
    title: string;
    duration: bigint;
    difficulty: Difficulty;
    quiz: Quiz;
    description: string;
    lessons: Array<Lesson>;
    category: Category;
}
export interface Course {
    id: CourseId;
    title: string;
    duration: bigint;
    difficulty: Difficulty;
    quiz: Quiz;
    description: string;
    lessons: Array<Lesson>;
    category: Category;
}
export type Time = bigint;
export interface Lesson {
    id: LessonId;
    title: string;
    content: string;
}
export type LessonId = bigint;
export interface UserProgressView {
    quizScores: Array<[bigint, bigint]>;
    lastActiveDay: Time;
    weeklyActivity: Array<[bigint, bigint]>;
    completedLessons: Array<bigint>;
    learningStreak: bigint;
}
export interface Quiz {
    id: QuizId;
    questions: Array<Question>;
}
export type CourseId = bigint;
export interface Question {
    question: string;
    correctAnswer: bigint;
    options: Array<string>;
}
export type QuizId = bigint;
export enum Category {
    Business = "Business",
    Design = "Design",
    Programming = "Programming",
    Science = "Science"
}
export enum Difficulty {
    Beginner = "Beginner",
    Advanced = "Advanced",
    Intermediate = "Intermediate"
}
export interface backendInterface {
    createCourse(courseInput: CourseInput): Promise<void>;
    getCourse(id: CourseId): Promise<Course>;
    getCourses(): Promise<Array<Course>>;
    getDailyChallenge(): Promise<Quiz>;
    getLessons(courseId: CourseId): Promise<Array<Lesson>>;
    getQuiz(courseId: CourseId): Promise<Quiz>;
    getUserProgress(user: Principal): Promise<UserProgressView>;
    markLessonComplete(courseId: CourseId, lessonId: LessonId): Promise<void>;
    submitQuizAnswers(courseId: CourseId, answers: Array<bigint>): Promise<bigint>;
}
import type { Category as _Category, Course as _Course, CourseId as _CourseId, CourseInput as _CourseInput, Difficulty as _Difficulty, Lesson as _Lesson, Quiz as _Quiz } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCourse(arg0: CourseInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(to_candid_CourseInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(to_candid_CourseInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCourse(arg0: CourseId): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_Course_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_Course_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyChallenge(): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyChallenge();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyChallenge();
            return result;
        }
    }
    async getLessons(arg0: CourseId): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessons(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessons(arg0);
            return result;
        }
    }
    async getQuiz(arg0: CourseId): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return result;
        }
    }
    async getUserProgress(arg0: Principal): Promise<UserProgressView> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress(arg0);
            return result;
        }
    }
    async markLessonComplete(arg0: CourseId, arg1: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async submitQuizAnswers(arg0: CourseId, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswers(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CourseId;
    title: string;
    duration: bigint;
    difficulty: _Difficulty;
    quiz: _Quiz;
    description: string;
    lessons: Array<_Lesson>;
    category: _Category;
}): {
    id: CourseId;
    title: string;
    duration: bigint;
    difficulty: Difficulty;
    quiz: Quiz;
    description: string;
    lessons: Array<Lesson>;
    category: Category;
} {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        difficulty: from_candid_Difficulty_n9(_uploadFile, _downloadFile, value.difficulty),
        quiz: value.quiz,
        description: value.description,
        lessons: value.lessons,
        category: from_candid_Category_n11(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
}): Difficulty {
    return "Beginner" in value ? Difficulty.Beginner : "Advanced" in value ? Difficulty.Advanced : "Intermediate" in value ? Difficulty.Intermediate : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Business: null;
} | {
    Design: null;
} | {
    Programming: null;
} | {
    Science: null;
}): Category {
    return "Business" in value ? Category.Business : "Design" in value ? Category.Design : "Programming" in value ? Category.Programming : "Science" in value ? Category.Science : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CourseInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseInput): _CourseInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    difficulty: Difficulty;
    quiz: Quiz;
    description: string;
    lessons: Array<Lesson>;
    category: Category;
}): {
    title: string;
    duration: bigint;
    difficulty: _Difficulty;
    quiz: _Quiz;
    description: string;
    lessons: Array<_Lesson>;
    category: _Category;
} {
    return {
        title: value.title,
        duration: value.duration,
        difficulty: to_candid_Difficulty_n3(_uploadFile, _downloadFile, value.difficulty),
        quiz: value.quiz,
        description: value.description,
        lessons: value.lessons,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
} {
    return value == Difficulty.Beginner ? {
        Beginner: null
    } : value == Difficulty.Advanced ? {
        Advanced: null
    } : value == Difficulty.Intermediate ? {
        Intermediate: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Business: null;
} | {
    Design: null;
} | {
    Programming: null;
} | {
    Science: null;
} {
    return value == Category.Business ? {
        Business: null
    } : value == Category.Design ? {
        Design: null
    } : value == Category.Programming ? {
        Programming: null
    } : value == Category.Science ? {
        Science: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
